openapi: "3.0.0"
info:
  title: VphereAPI
  version: "1.0"
  description: Vphere后端api文档
servers:
  - url: "http://{domain}/{basePath}"
    description: Vphere api
    variables:
      domain:
        description: API服务器域名
        default: vphere.yanmy.top
        enum:
          - vphere.yanmy.top
          - vpheretest.yanmy.top
      basePath:
        description: API服务器地址
        default: api
# 全局认证
security:
  - cookieAuth: []
tags:
  - name: user
    description: 用户 API
  - name: group
    description: 集体 API
  - name: signin
    description: 签到 API
paths:
  /user/login:
    post:
      tags: 
        - user
      summary: 登录
      description: 微信code登录
      security: []
      requestBody:
        description: 请求参数
        required: true
        content: 
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                code:
                  description: 微信小程序code
                  type: string
                nick_name:
                  description: 微信昵称
                  type: string
                avatarUrl:
                  description: 微信头像地址
                  type: string
      responses:
        "200":
          description: 登录成功,返回cookies名为vphere,你需要在后续请求中添加cookies字段,填入该返回值
          headers: 
            Set-Cookie:
              description: 设置cookies
              schema: 
                type: string
                example: vphere=abcde12345; Path=/; HttpOnly
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    $ref: "#/components/schemas/code"
                  status:
                    $ref: "#/components/schemas/status"
                  data:
                    type: string
                    example: 成功       
        "403":
          description: 登录失败
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /user/schedule:
    get:
      tags: 
        - user
      summary: 获取用户考勤表
      description: 获取用户的考勤时间表
      responses:
        "200":
          description: 成功,返回用户考勤表
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    $ref: "#/components/schemas/code"
                  status:
                    $ref: "#/components/schemas/status"
                  data:
                    $ref: "#/components/schemas/schedule"
                      
        "401":
          $ref: "#/components/responses/NotAuthorization"
        "403":
          $ref: "#/components/responses/InvalidProperties"
  /user/attendance:
    get:
      tags: 
        - user
      summary: 获取用户考勤情况
      description: 获取用户的考勤情况
      responses:
        "200":
          description: 成功,返回用户缺席记录,只有缺席过的集体才会记录
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    $ref: "#/components/schemas/code"
                  status:
                    $ref: "#/components/schemas/status"
                  data:
                    $ref: "#/components/schemas/attendance"
        "401":
          $ref: "#/components/responses/NotAuthorization"
        "403":
          $ref: "#/components/responses/InvalidProperties"
  /user/manage:
    get:
      tags: 
        - user
      summary: 获取用户管理的小集体
      description: 获取用户管理的小集体
      responses:
        "200":
          description: 获取成功
          content:
            application/json:
                schema:
                  type: object
                  properties:
                    code:
                      $ref: "#/components/schemas/code"
                    status:
                      $ref: "#/components/schemas/status"
                    data:
                      $ref: "#/components/schemas/Usermanage" 
        "401":
          $ref: "#/components/responses/NotAuthorization"
        "403":
          $ref: "#/components/responses/InvalidProperties"
  /group/create:
    post:
      tags: 
        - group
      summary: 创建集体
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/CreatGroup"
      responses:
        "200":
          $ref: "#/components/responses/success"
        "401":
          $ref: "#/components/responses/NotAuthorization"
        "403":
          $ref: "#/components/responses/InvalidProperties"
  /group/join:
    post:
      tags: 
        - group
      summary: 加入集体
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/JoinGroup"
      responses:
        "200":
          $ref: "#/components/responses/success"
        "401":
          $ref: "#/components/responses/NotAuthorization"
        "403":
          $ref: "#/components/responses/InvalidProperties"       
  /group/joined:
    get:
      tags:
        - group
      summary: 加入了的集体
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    $ref: "#/components/schemas/code"
                  status:
                    $ref: "#/components/schemas/status"
                  data:
                    $ref: "#/components/schemas/joined"
        "401":
          $ref: "#/components/responses/NotAuthorization"
  /group/manage:
    get:
      tags:
        - group
      summary: 获取用户管理的集体
      responses:
        "200":
          description: 成功,返回用户管理的小集体,group_status为0表示小集体,1表示大集体
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    $ref: "#/components/schemas/code"
                  status:
                    $ref: "#/components/schemas/status"
                  data:
                    $ref: "#/components/schemas/Groupmanage"
        "401":
          $ref: "#/components/responses/NotAuthorization"
  /group/small/situation:
    get:
      tags:
        - group
      summary: 小集体签到情况
      parameters: 
        - name: groupid
          description: 集体id
          required: true
          in: path
          schema:
            type: integer
            example: 1
      responses:
        "200":
          $ref: "#/components/responses/Excel"
        "401":
          $ref: "#/components/responses/NotAuthorization"
  /group/large/situation:
    get:
      tags:
        - group
      summary: 大集体签到情况
      parameters: 
        - name: groupid
          description: 集体id
          required: true
          in: path
          schema:
            type: integer
            example: 1
      responses:
        "200":
          $ref: "#/components/responses/Excel"
        "401":
          $ref: "#/components/responses/NotAuthorization"
  /group/small_group:
    get:
      tags:
        - group
      summary: 获取系统内已有小集体
      security: []
      responses:
        "200":
          $ref: "#/components/responses/success"
        "401":
          $ref: "#/components/responses/NotAuthorization"
  /group/large_group:
    get:
      tags:
        - group
      summary: 获取系统内已有大集体
      security: []
      responses:
        "200":
          $ref: "#/components/responses/success"
        "401":
          $ref: "#/components/responses/NotAuthorization"
        
  /sign/in:
    post:
      tags:
       - signin
      summary: 签到
      requestBody:
        content: 
            multipart/form-data:
              schema:
                properties:
                  groupid: 
                    type: integer
                    description: 集体id
                  signid: 
                    type: integer
                    description: 签到记录id
                  vfile: 
                    type: string
                    format: binary
                    description: 录音文件
                  location:
                    $ref: "#/components/schemas/location"
      responses:
        "200":
          $ref: "#/components/responses/success"
  /sign/reg:
    post:
      tags:
       - signin
      summary: 声纹注册
      requestBody:
        content: 
            multipart/form-data:
              schema:
                properties:
                  vfile: 
                    type: string
                    format: binary
                    description: 录音文件
      responses:
        "200":
          $ref: "#/components/responses/success"
  /sign/create: 
    post:
      tags:
       - signin
      summary: 添加签到
      requestBody:
        content: 
            application/x-www-form-urlencoded:
              schema:
                properties:
                  groupid: 
                    type: integer
                    description: 集体id
                  start_time:
                    type: integer
                    description: 签到开始时间,时间戳
                  end_time:
                    type: integer
                    description: 签到结束时间,时间戳
                  location:
                    $ref: "#/components/schemas/location"
      responses:
        "200":
          $ref: "#/components/responses/success"
  /sign/status:
    get:
      tags:
        - signin
      summary: 声纹注册信息
      description: 获取声纹注册状态和剩余修改次数                
      responses:
        "200":
          description: 成功,返回声纹注册状态
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    $ref: "#/components/schemas/code"
                  status:
                    $ref: "#/components/schemas/status"
                  data:
                    $ref: "#/components/schemas/Signstatus"
components:
  securitySchemes:
    cookieAuth:         # arbitrary name for the security scheme; will be used in the "security" key later
      type: apiKey
      in: cookie
      name: vphere  # cookie name
  schemas:
    code:
      description: 状态码
      type: integer
      example: 200
    status:
      description: 状态信息
      type: string
      example: OK
    Error:
      description: 错误返回信息
      type: object
      properties:
        error:
          description: 详细错误信息
          type: string    
    CreatGroup:
      type: object
      properties:
        name:
          description: 集体名称
          type: string
        belong:
          description: 所属大集体,0就是大集体,1-n为集体
          type: integer
    JoinGroup:
      type: object
      properties:
        groupid:
          description: 集体id
          type: integer
    location:
      type: object
      description: 签到位置
      properties:
        name: 
          type: string
          description: 地点名
        address: 
          type: string
          description: 地点
        latitude: 
          type: number
          description: 纬度
        longitude: 
          type: number
          description: 纬度
    schedule:
      type: object
      properties: 
        group1:
          type: object
          properties:
            group_name:
              type: string
              example: 高数
            start_time:
              type: string
              example: 2020-05-15 16:33:29
            end_time:
              type: string
              example: 2020-05-15 22:33:28
            status:
              type: string
              example: 已签到
            locataion: 
              type: string
              example: 湘大逸夫楼
        group2:
          type: object
          properties:
            group_name:
              type: string
              example: 英语
            start_time:
              type: string
              example: 2020-05-16 13:33:29
            end_time:
              type: string
              example: 2020-05-16 15:22:28
            status:
              type: string
              example: 未签到
            locataion: 
              type: string
              example: 湘大逸夫楼
        group3:
          type: object
          properties:
            group_name:
              type: string
              example: 数据库
            start_time:
              type: string
              example: 2020-05-18 13:33:29
            end_time:
              type: string
              example: 2020-05-18 15:22:28
            status:
              type: string
              example: 已迟到
            locataion: 
              type: string
              example: 湘大逸夫楼       
    attendance:
      type: object
      properties:
        group1:
          type: object
          properties:
            group_name:
              type: string
              example: 高数
            times:
              type: integer
              description: 缺席次数
              example: 2  
        group2:
          type: object
          properties:
            group_name:
              type: string
              example: 英语
            times:
              type: integer
              description: 缺席次数
              example: 1  
    Usermanage:
      type: object
      properties:
        group1:
          type: object
          properties:
            id:
              type: integer
              description: 集体id
              example: 2 
            group_name:
              type: string
              example: 高数
        group2:
          type: object
          properties:
            id:
              type: integer
              description: 集体id
              example: 12 
            group_name:
              type: string
              example: 英语 
    joined:
      type: object
      properties:
        group1:
          type: object
          properties:
            id:
              type: integer
              description: 集体id
              example: 2 
            group_name:
              type: string
              example: 高数
        group2:
          type: object
          properties:
            id:
              type: integer
              description: 集体id
              example: 12 
            group_name:
              type: string
              example: 英语          
    Groupmanage:
      type: object
      properties:
        group1:
          type: object
          properties:
            id:
              type: integer
              description: 集体id
              example: 2 
            group_name:
              type: string
              example: 高数
            group_status:
              type: integer
              example: 0  
        group2:
          type: object
          properties:
            id:
              type: integer
              description: 集体id
              example: 2 
            group_name:
              type: string
              example: 计算机学院
            group_status:
              type: integer
              example: 1  
    Signstatus:
      type: object
      properties:
        status:
          type: string
          example: 未注册
          description: 声纹注册状态,已注册,未注册,注册中
        times:
          type: string
          example: 3
          description: 剩余声纹注册次数
  responses:
    #200
    success:
      description: 成功
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                $ref: "#/components/schemas/code"
              status:
                $ref: "#/components/schemas/status"
              data:
                type: string
                example: 成功
    Excel:
      description: A Excel file
      content:
        application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
          schema:
            type: string
            format: binary

    # 401
    NotAuthorization:
      description: 未登录
    # 403
    InvalidProperties:
      description: 参数不满足
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            error: "参数缺失"
    IllegalContent:
      description: 内容非法
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            error: 内容包含敏感词“xxx”
    NoPermission:
      description: 当前用户无权限
    # 404
    NotFound:
      description: 指定数据不存在   





externalDocs:
  url: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md
  description: OpenApi 3.0.2 文档
